<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="http://leeknow.kz/soap/payment"
           xmlns:tns="http://leeknow.kz/soap/payment"
           elementFormDefault="qualified">

    <xs:simpleType name="PaymentStatus">
        <xs:restriction base="xs:string">
            <xs:enumeration value="SUCCESS"/>
            <xs:enumeration value="FAILED"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:element name="GetPaymentRequest">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="paymentId" type="xs:int"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="GetPaymentResponse">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="status" type="tns:PaymentStatus"/>
                <xs:element name="created" type="xs:dateTime"/>
                <xs:element name="completed" type="xs:dateTime" minOccurs="0"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

</xs:schema>
