server:
  port: 8080

spring:
  application:
    name: gateway
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: "http://localhost:8084/.well-known/jwks.json"
  cloud:
    gateway:
      server:
        webmvc:
          routes:
            - id: order-service
              uri: lb://order-service
              predicates:
                - Path=/orders/**
            - id: user-auth-service
              uri: lb://user-service
              predicates:
                - Path=/auth/**
            - id: user-service-main
              uri: lb://user-service
              predicates:
                - Path=/users/**
            - id: file-service
              uri: lb://file-service
              predicates:
                - Path=/files/**

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
